// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MonitoringService.Data;

#nullable disable

namespace MonitoringService.Migrations
{
    [DbContext(typeof(MonitoringDbContext))]
    [Migration("20250530222741_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MonitoringService.Models.Alert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime?>("AcknowledgedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("AcknowledgedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("AlertDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ResolutionNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ResolvedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Severity")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("TriggeringClinicalEntryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("AlertDateTime")
                        .HasDatabaseName("IX_Alert_AlertDateTime");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("IX_Alert_PatientId");

                    b.HasIndex("Severity")
                        .HasDatabaseName("IX_Alert_Severity");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Alert_Status");

                    b.HasIndex("PatientId", "Status")
                        .HasDatabaseName("IX_Alert_PatientId_Status");

                    b.HasIndex("Severity", "Status")
                        .HasDatabaseName("IX_Alert_Severity_Status");

                    b.ToTable("Alerts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("55ecf745-209d-4698-b948-ecc148a7b42a"),
                            AlertDateTime = new DateTime(2025, 5, 30, 20, 27, 40, 669, DateTimeKind.Utc).AddTicks(9654),
                            CreatedAt = new DateTime(2025, 5, 30, 20, 27, 40, 669, DateTimeKind.Utc).AddTicks(9660),
                            Description = "Patient's blood pressure reading (150/95) exceeds normal range",
                            PatientId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Severity = 2,
                            Status = 1,
                            Title = "High Blood Pressure Alert",
                            UpdatedAt = new DateTime(2025, 5, 30, 20, 27, 40, 669, DateTimeKind.Utc).AddTicks(9661)
                        },
                        new
                        {
                            Id = new Guid("76b5cb1d-8ce4-4446-b1bb-ea8014716994"),
                            AcknowledgedAt = new DateTime(2025, 5, 30, 17, 27, 40, 669, DateTimeKind.Utc).AddTicks(9666),
                            AcknowledgedBy = "Dr. Michael Johnson",
                            AlertDateTime = new DateTime(2025, 5, 30, 16, 27, 40, 669, DateTimeKind.Utc).AddTicks(9664),
                            CreatedAt = new DateTime(2025, 5, 30, 16, 27, 40, 669, DateTimeKind.Utc).AddTicks(9669),
                            Description = "Patient temperature (38.5°C) indicates potential fever",
                            PatientId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Severity = 3,
                            Status = 2,
                            Title = "Elevated Temperature",
                            UpdatedAt = new DateTime(2025, 5, 30, 17, 27, 40, 669, DateTimeKind.Utc).AddTicks(9670)
                        },
                        new
                        {
                            Id = new Guid("d1f713db-d10f-474d-a889-448675d907ed"),
                            AcknowledgedAt = new DateTime(2025, 5, 30, 10, 27, 40, 669, DateTimeKind.Utc).AddTicks(9674),
                            AcknowledgedBy = "Nurse Jane Smith",
                            AlertDateTime = new DateTime(2025, 5, 29, 22, 27, 40, 669, DateTimeKind.Utc).AddTicks(9671),
                            CreatedAt = new DateTime(2025, 5, 29, 22, 27, 40, 669, DateTimeKind.Utc).AddTicks(9676),
                            Description = "Patient has missed scheduled medication doses",
                            PatientId = new Guid("33333333-3333-3333-3333-333333333333"),
                            ResolutionNotes = "Spoke with patient, medication schedule clarified",
                            ResolvedAt = new DateTime(2025, 5, 30, 14, 27, 40, 669, DateTimeKind.Utc).AddTicks(9674),
                            ResolvedBy = "Nurse Jane Smith",
                            Severity = 2,
                            Status = 4,
                            Title = "Medication Adherence Concern",
                            UpdatedAt = new DateTime(2025, 5, 30, 14, 27, 40, 669, DateTimeKind.Utc).AddTicks(9677)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
